version: 2
plan:
  project-key: CON
  key: PLAN
  name: My Plan

stages:
  - Build Package:
      jobs:
        - Buildit

Buildit:
  tasks:
    - clean
    - scripts:
        - dotnet build
        - dotnet publish
            